# Generated by Django 3.1.6 on 2021-06-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('adhaar_number', models.CharField(max_length=80)),
            ],
        ),
    ]
