# Generated by Django 3.1.6 on 2021-06-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='name',
        ),
        migrations.AddField(
            model_name='details',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='adhaar_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='details',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='details',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
