# Generated by Django 3.1.6 on 2021-06-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_details_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
