# Generated by Django 3.1.6 on 2021-06-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20210606_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='number',
        ),
        migrations.AddField(
            model_name='detail',
            name='branch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='rollnumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='adhaar_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
